# Generated by Django 2.1.7 on 2019-05-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20190515_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mode',
            new_name='mood',
        ),
    ]
