# Generated by Django 2.1.7 on 2019-05-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20190515_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mood',
            field=models.CharField(default='listener', max_length=50),
        ),
    ]
